export const SOCKET_EVENTS = {
  ROOMS_LIST: "roomsList",
  ERROR_MESSAGE: "errorMessage",
  ROOM_CREATED: "roomCreated",
  JOINED_ROOM: "joinedRoom",
  USER_JOINED: "userJoined",
  SHOW_BANNER: "showBanner",
  START_QUIZ: "startQuiz",
  PAUSE_TYPEWRITER: "pauseTypewriter",
  BUZZED: "buzzed",
  PARTIAL_FEEDBACK: "partialFeedback",
  ANSWER_RESULT: "answerResult",
  NEXT_QUESTION: "nextQuestion",
  REQUEST_RESUME: "requestResume",
  RESUME_TYPEWRITER: "resumeTypewriter",
  QUIZ_ENDED: "quizEnded",
  GET_ROOMS: "getRooms",
  SET_NAME: "setName",
  CREATE_ROOM: "createRoom",
  JOIN_ROOM: "joinRoom",
  BEGIN_QUIZ: "beginQuiz",
  BUZZ: "buzz",
  SUBMIT_CHAR: "submitChar",
};
